### PR TITLE
Makefile patchset

### PR DESCRIPTION
**Pull request by EliteTK**
This set of patches attempts to do some general cleanup, improvements and simplification of the makefile.

Each commit has a full justification in its full message and should be unambiguous in what it tries to do.

Feel free to cherry pick commits you like while discarding ones you do not wish to accept.

If you wish for me to make changes to any commit or notice an issue, it will be no problem for me to update the PR.

Thanks.

### CODE REVIEW

**Comment by krpors** [comment]
These are all pretty great tbh, but it introduced a bit of 'magic' of `make` which I do not (yet) fully understand, such as the `?=` and `!=` notation, and the usage of `-MMD` and `-MP`, although I've heard of them. I'll need to check it out a bit in documentation of make, but all in all these are good additions, especially with the comments provided in the commits(!).

One other thing: I'm not entirely sure about the install target: when running `make install` it will install the manpage as `/usr/local/man/man1`:

    $ file /usr/local/man/man1
    /usr/local/man/man1: gzip compressed data, was "hx.1", last modified: Thu Dec  1 19:12:18 2016, from Unix

It probably has something to do with the `-D` argument of `install`.

**Comment by EliteTK** [comment]
Phew, that was a bit of a rebase, but I rebased my changes over your recent makefile change to save you some sweat.

Now onto your questions:

`!=` is called the shell assignment operator, it evaluates the right hand side as if it was in a $(shell ...) command and assigns the result to the variable.

`?=` is called the conditional variable assignment operator, it assigns only if the variable is not yet defined. = and := all do various things depending on if a variable has been previously assigned or not (even varies between if it was passed via the environment, or as a command line argument). ?= explicitly only sets if the "origin" of the variable is "undefined" (the variable has never been defined before).

Yes, that install target thing is a bug, give me a moment and I'll fix it, I totally forgot about installing to empty directory structures, there are two options to fix it:

    install -Dm644 ./hx.1.gz -t $(DESTDIR)$(PREFIX)$(mandir)/man1

or

    install -Dm644 ./hx.1.gz $(DESTDIR)$(PREFIX)$(mandir)/man1/hx.1.gz

I'm not sure yet which one to go for, I'm personally leaning for the former as it doesn't repeat the file name but since you're active on GH, I might as well ask you what you think.

(Edit: Actually I've already made the change to use -t so when you're ready I'll push --force my updated PR) (This is actually one of the only good times to use push --force, you might want to pull --force when pulling my branch for testing.)

**Comment by krpors** [comment]
Yeah, I made some changes, then received a notification about yours :) Anyway, thanks for the explanations!

I guess your first suggestion is the better one. Like you said, it prevents filename repetition.

**Comment by EliteTK** [comment]
Well, a word of warning then: I'll be sending in the change now. (Sorry about that, it seems this github allowing maintainers to edit pulls is a new thing and it threw me off.)

Edit: and it's done.

I'm happy with you making any minor changes you wish to make at this point. But remember, you can always ask me to do them :P

**Comment by EliteTK** [comment]
Incidentally, just in case you missed it: I fixed the install target issue. (The discussion went really quiet, that's all.)

**Comment by krpors** [comment]
Yeah discussion went quiet, had to get my sleep for the day :P Thanks! I'll check it out soon.

**Comment by EliteTK** [comment]
Oh, and I saw I forgot to explain -MMD -MP. The GCC man page can be a bit difficult to follow for these so here's the abridged version:

-M makes gcc switch from what it normally does (output your object file) to outputting a rule suitable for passing to make, this rule contains the object file which would be the target of the compilation, a colon and then a list of header files the source file of that object file includes.

another -M means gcc doesn't include system header files in this list (usually there's not much need to worry about these but sometimes you might want to drop the second -M)

So gcc -MM while compiling main.c would output something like:

    main.o: main.c editor.h util.h undo.h

-MD makes gcc do what -M does as a side-effect instead of replacing the normal functionality, and output the result to the file name passed via -o with the .o replaced with .d. (So for main above, the output would go to main.d).

Combining -MD and -MM does what you'd expect.

Finally, -MP adds phony targets for all header files in the rule. For example:

    main.o: main.c editor.h util.h undo.h
    
    editor.h:
    
    util.h:
    
    undo.h:

This avoids errors from make when header files are renamed or removed.

Finally, in the makefile there's a `-include $(objects:.o=.d)`

The `include` part does what you'd expect, the - just means it doesn't complain on error (missing files).

**Comment by krpors** [comment]
Took some time (work, holiday, whatever), but finally merged! Thanks.

**Pull request merged**
