### PR TITLE
Implement byte search

### LINKED ISSUE #13: Byte search syntax
I wouldn't mind giving non-ASCII byte searching a shot. Though I'm not sure what the intented syntax is. editor.c seems to imply any search string starting with "0x" should be regarded as a hex byte sequence though of course this means searching for "0x" is impossible.

Here are the options I think could be possible... the existing input buffer size is 80 and I might make reference to that.

**A separate search command**
That is, instead of /, some other key.
Advantages
- Straightforward to implement (convert typed bytes into actual bytes and use existing search process)
- No extra typing (i.e. no need for \x or 0x) so 40 bytes fit
- No need for a character to become an escape character

Disadvantages
- Not possible to mix bytes and ASCII without typing the hex ASCII value ((e.g. 41 instead of A)
- Creates a separate command

**\x regards the entire search stirng as byte values**
So "/\xabcf" searches for 0xab follow by 0xcf.
Advantages
- Uses same command
- No extra typing past initial "\x", so 39 bytes fit

Disadvantages
- Not possible to mix bytes and ASCII without typing the hex ASCII value
- \ becomes an escape character - though if \ appears in a position after the first, it's not an issue.

**\x regards the following two bytes as a byte value**
So "/a\x41b" searches for a followed by 0x41 followed by b.
Advantages
- Can mix ASCII and byte values
- Uses same command
- Pretty simple to explain in documentation

Disadvantages
- \x needs to be typed before every byte value so a maximum of 20 byte values can be searched (or 19 byte values and 4 ASCII characters, and so on)
- \ becomes an escape character anywhere in the string - \\ is required to search for \ and ' followed by anything but x or \ is an error that needs to be handled

\x can be replaced by 0x though I think making 0 an escape character would be frustrating as it isn't standard (as far as I've seen at least).

### PR DESCRIPTION
**Pull request by mbarbar**
This closes #13 

A new function `parse_search_string`, copies its input to another string, but only one byte per "object". So standard keyboard characters just get copied over, \xXY gets copied as a single byte, and \\\\ gets copied as \\. A new enum `parse_errors` defines possible errors and these are returned.

`editor_process_search` is modified to handle report the parsing errors, if any, and to search on the parsed string instead of the one from the user.

### CODE REVIEW

**Comment by krpors** [comment]
Phew, finally got time to take a look :) So far, thanks for the effort of looking into it!

I'm currently just testing the functionality and there's one flaky thing going on: when entering a search string like this:

    \x6c\x00\x00\x00\x12

It will only search for the `\x6c`. It's pretty obvious that it works this way since you're using `strlen`, which will stop after the first byte since it contains the `\0` character at that position. I think the easiest way is to use the `charbuf` struct plus its functions so it can contain the `\0` character. 

Thoughts?

**Comment by mbarbar** [comment]
Good catch, that was a big oversight.

I changed it to a charbuf as you suggested. Had to make a few changes (early exits->`break` for example) because it's allocated on the heap. My biggest concern is `#include "charbuf.h"` in `util.h` in that it makes `util` less self contained. Do you think that's an issue?

I also went ahead and documented the search syntax, which I had forgotten to do before. Though I'm unsure if it's better suited elsewhere within the README/man page.

**Comment by mbarbar** [comment]
I was looking through some other code, and it suddenly occured to me, parse_search_string really doesn't belong in `util` as it's too specific. So I moved it over to `editor`.

**Comment by krpors** [comment]
Finally came around to looking into this :) Looking good! Just merged it into the upstream develop branch. Thanks for the work!!

**Pull request merged**
