### PR TITLE
fix MacOS build

### PR DESCRIPTION
**Pull request by 5HT**

### CODE REVIEW

**Comment by krpors** [comment]
Hey thanks for your PR. Is there any other way to fix this without adding that compiler flag? For instance, is it complaining on an implicit function declaration which can be fixed in perhaps another way?

**Comment by 5HT** [comment]
Maybe. I just want to say that `hx` is beautiful! <3

**Comment by krpors** [comment]
Thanks :) 

I have no Mac to test this on. Do you have some output to see why the build fails?

**Comment by 5HT** [comment]
I moved to my own tree https://github.com/5HT/be and seems problem disappeared. I have plain Makefile:

```
objects := editor.o buffer.o terminal.o hex/hex.o dasm/dasm.o \
	x86/insnsd.o x86/insnsa.o x86/insnsb.o x86/insnsn.o x86/disasm.o \
	x86/regdis.o x86/regs.o x86/regflags.o x86/regvals.o \
	x86/iflag.o x86/sync.o x86/disp8.o x86/nctype.o x86/readnum.o  \
	x86/common.o x86/alloc.o x86/string.o \
	x86/warnings.o x86/error.o x86/ver.o

all: be x86/be-dasm
x86/be-dasm: $(objects) x86/be-dasm.o
be: $(objects) be.o

clean:
	$(RM) $(objects) be.o x86/be-dasm.o $(objects:.o=.d) be x86/be-dasm
```

**Comment by krpors** [comment]
Then I will close this PR without merging. 

By the way, I got several messages from users that you used my code in your project(s). It's open source by definition and I encourage re-use, but please read the license and at least make some reference to the original code and author(s) and license. 

Thanks!

**Comment by 5HT** [comment]
I gave credits in README starting from <a href="https://github.com/5HT/be/commit/f4bf61be8f3b780f65690e9f590bee75f20883c5">initial commits</a>. Let me know if you insist including MIT license which I can't afford for russian community, especially for InsoSec editor. I will anyway rewrite it as it renders full screen but not selective character changings, and I will need my own windowed buffer for disk sector editing.

**Comment by 5HT** [comment]
As for your user requests I already gave official answer there is no need for stalking.
https://tonpa.guru/stream/2022/2022-04-10%20Russian%20War%20against%20Groupoid%20Infinity.htm
This is full scale war initiated by one of my student.

**Pull request closed without merging**
